# Generated by Django 4.1.4 on 2023-01-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gaseosas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('stock', models.BooleanField(default=True, verbose_name='en stock')),
            ],
            options={
                'verbose_name': 'Gaseosa',
                'verbose_name_plural': 'Gaseosas',
            },
        ),
    ]
