# Generated by Django 4.1.4 on 2023-01-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
