# Generated by Django 4.1.4 on 2023-01-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzas',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='precio',
            field=models.IntegerField(verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='stock',
            field=models.BooleanField(verbose_name='en stock'),
        ),
    ]
