# Generated by Django 4.1.4 on 2023-02-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_pizza', '0003_alter_pizzas_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
    ]
